name: Test/Fmt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install cairo-lang and deps
      run: pip install -r requirements.txt

    - name: build
      run: make build

    - name: test
      run: make coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: format
      run: make check_fmt

    - name: Compare trace & memory with cairo-vm
      run: make compare_trace_memory

    - name: Compare trace & memory with cairo-vm in proof mode
      run: make compare_proof_trace_memory

  demos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install cairo-lang and deps
      run: pip install -r requirements.txt
    
    - name: Run fibonacci demo
      run: make demo_fibonacci
    
    - name: Run factorial demo
      run: make demo_factorial
