name: Test/Fmt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install cairo-lang and deps
      run: pip install -r requirements.txt

    - name: test
      run: make test

    - name: format
      run: make check_fmt
